COMPONENT=CatracaRootAppC
PFLAGS+=-DRF230_DEF_CHANNEL=26
PFLAGS+=-DCC2420_DEF_CHANNEL=26 
CFLAGS += -I$(TOSDIR)/lib/net \
	  -I$(TOSDIR)../Catraca \
          -I$(TOSDIR)/lib/net/le \
          -I$(TOSDIR)/lib/net/ctp \
          -I$(TOSDIR)/lib/printf
include $(MAKERULES)
